spring.application.name=user-service
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&permitMysqlScheme=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# --- Eureka Service Discovery ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=User Service
info.app.version=1.0.0

# JWT konfiguracija — asimetricna enkripcija (RS256)
# Privatni kljuc koristi user-service za potpisivanje tokena.
# U produkciji: cuvati u environment varijabli ili vault-u, nikad commitovati u git!
jwt.private-key-file=src/main/resources/private_key.pem
# Token istice za 1 sat (3600000 ms)
jwt.expiration-ms=3600000

# ===================================================================
# --- RabbitMQ Konfiguracija (Zadatak 8) ---
# ===================================================================
# Adresa masine na kojoj radi Docker sa RabbitMQ serverom
spring.rabbitmq.host=localhost
# Port koji Spring koristi za slanje i primanje poruka
spring.rabbitmq.port=5672
# Podrazumijevani login za pristup RabbitMQ
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

#Vrijeme cekanja na povezivanje
spring.rabbitmq.connection-timeout=5000