spring.application.name=eureka-server
server.port=8761

# Ne registruj server samog sebe kao klijenta
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN

# Actuator
management.endpoints.web.exposure.include=health,info
